# Generated by Django 4.0.3 on 2022-05-19 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('gene_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('gene_name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('transcript_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('transcript_name', models.CharField(max_length=50, null=True)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gene')),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptExon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('exon_region_type', models.CharField(choices=[('TRANSLATED', 'TRANSLATED'), ('UNTRANSLATED_OR_UNKNOWN', 'UNTRANSLATED_OR_UNKNOWN'), ('NOVEL_TRANSCRIPT', 'NOVEL_TRANSCRIPT'), ('NOVEL_EXON', 'NOVEL_EXON')], max_length=23)),
                ('intron_region_type', models.CharField(choices=[('KNOWN_JUNCTION', 'KNOWN_JUNCTION'), ('NOVEL_JUNCTION', 'NOVEL_JUNCTION'), ('NO_JUNCTION', 'NO_JUNCTION')], max_length=14)),
                ('intron_end', models.IntegerField(null=True)),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.transcript')),
            ],
        ),
        migrations.CreateModel(
            name='ExpressionLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.IntegerField()),
                ('expression_level', models.FloatField()),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.transcript')),
            ],
        ),
        migrations.CreateModel(
            name='DnaExon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('intron_end', models.IntegerField(null=True)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gene')),
            ],
        ),
        migrations.CreateModel(
            name='Coverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('down_sample_percent', models.FloatField()),
                ('illumina_average_coverage', models.FloatField()),
                ('nanopore_average_coverage', models.FloatField()),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gene')),
            ],
        ),
    ]
