# Generated by Django 4.0.3 on 2022-05-19 17:50

from django.db import migrations

from api.migrations import insert_objects, delete_objects

GENES_TABLE_PATH: str = 'api/migrations/data/genes.csv'
MODEL_CLASS_NAME: str = 'Gene'


def _insert_genes(apps, _):
    insert_objects(apps=apps, model_class_name=MODEL_CLASS_NAME, df_path=GENES_TABLE_PATH)


def _delete_genes(apps, _):
    delete_objects(apps=apps, model_class_name=MODEL_CLASS_NAME)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(_insert_genes, _delete_genes)
    ]
