# Generated by Django 4.0.3 on 2022-05-19 21:31

from django.db import migrations

from api.migrations import insert_objects, delete_objects

TRANSCRIPTS_TABLE_PATH: str = 'api/migrations/data/transcripts.csv'
MODEL_CLASS_NAME: str = 'Transcript'


def _insert_transcripts(apps, _):
    insert_objects(apps=apps, model_class_name=MODEL_CLASS_NAME, df_path=TRANSCRIPTS_TABLE_PATH)


def _delete_transcripts(apps, _):
    delete_objects(apps=apps, model_class_name=MODEL_CLASS_NAME)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_insert_genes'),
    ]

    operations = [
        migrations.RunPython(_insert_transcripts, _delete_transcripts)
    ]
