# Generated by Django 4.0.3 on 2022-05-19 21:37

from django.db import migrations


from api.migrations import insert_objects, delete_objects

EXPRESSION_LEVELS_TABLE_PATH: str = 'api/migrations/data/expression_levels.csv'
MODEL_CLASS_NAME: str = 'ExpressionLevel'


def _insert_expression_levels(apps, _):
    insert_objects(apps=apps, model_class_name=MODEL_CLASS_NAME, df_path=EXPRESSION_LEVELS_TABLE_PATH)


def _delete_expression_levels(apps, _):
    delete_objects(apps=apps, model_class_name=MODEL_CLASS_NAME)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_insert_transcripts'),
    ]

    operations = [
        migrations.RunPython(_insert_expression_levels, _delete_expression_levels)
    ]
