# Generated by Django 4.0.3 on 2022-05-19 21:45

from django.db import migrations


from api.migrations import insert_objects, delete_objects

DNA_EXONS_TABLE_PATH: str = 'api/migrations/data/dna_exons.csv'
MODEL_CLASS_NAME: str = 'DnaExon'


def _insert_dna_exons(apps, _):
    insert_objects(apps=apps, model_class_name=MODEL_CLASS_NAME, df_path=DNA_EXONS_TABLE_PATH)


def _delete_dna_exons(apps, _):
    delete_objects(apps=apps, model_class_name=MODEL_CLASS_NAME)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_insert_expression_levels'),
    ]

    operations = [
        migrations.RunPython(_insert_dna_exons, _delete_dna_exons)
    ]
