# Generated by Django 4.0.3 on 2022-05-19 22:40

from django.db import migrations


from api.migrations import insert_objects, delete_objects

COVERAGES_TABLE_PATH: str = 'api/migrations/data/coverages.csv'
MODEL_CLASS_NAME: str = 'Coverage'


def _insert_coverages(apps, _):
    insert_objects(apps=apps, model_class_name=MODEL_CLASS_NAME, df_path=COVERAGES_TABLE_PATH)


def _delete_coverages(apps, _):
    delete_objects(apps=apps, model_class_name=MODEL_CLASS_NAME)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_insert_dna_exons'),
    ]

    operations = [
        migrations.RunPython(_insert_coverages, _delete_coverages)
    ]
