# Generated by Django 4.0.3 on 2022-05-19 23:39

from django.db import migrations


from api.migrations import insert_objects, delete_objects

TRANSCRIPT_EXONS_TABLE_PATH: str = 'api/migrations/data/transcript_exons.csv'
MODEL_CLASS_NAME: str = 'TranscriptExon'


def _insert_transcript_exons(apps, _):
    insert_objects(apps=apps, model_class_name=MODEL_CLASS_NAME, df_path=TRANSCRIPT_EXONS_TABLE_PATH)


def _delete_transcript_exons(apps, _):
    delete_objects(apps=apps, model_class_name=MODEL_CLASS_NAME)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_insert_coverages'),
    ]

    operations = [
        migrations.RunPython(_insert_transcript_exons, _delete_transcript_exons)
    ]
